ManagementConsole:
  sha:
  release: 24.10-stable

MarketplaceItems:
  - name: unity-cs-monitoring-lambda
    version: 24.4-stable
  - name: unity-apigateway
    version: 24.4-stable
  - name: unity-proxy
    version: 24.4-stable
  - name: unity-ui
    version: 24.4-stable
