ManagementConsole:
sha:
release: 24.10-stable

MarketplaceItems:
  - name: unity-cs-monitoring-lambda
    version: 0.1
  - name: unity-apigateway
    version: 0.4
  - name: unity-proxy
    version: 0.14
  - name: unity-ui
    version: 0.8.0
